name: ptsi_bot_2
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {english_words: ^4.0.0, html: ^0.15.1, http: ^0.13.5, image: ^4.0.15, nyxx: ^4.5.0, nyxx_commands: ^4.3.0, nyxx_interactions: ^4.5.0, nyxx_lavalink: ^3.1.0, path: ^1.8.3, vector_math: ^2.1.4}

